export const SET_GAME_STATE = 'SET_GAME_STATE';
export type SET_GAME_STATE = typeof SET_GAME_STATE;

export const FETCH_POKEMON_API = 'FETCH_POKEMON_API';
export type FETCH_POKEMON_API = typeof FETCH_POKEMON_API;

export const POKEMON_API_FETCH_SUCCESSFUL = 'POKEMON_API_FETCH_SUCCESSFUL';
export type POKEMON_API_FETCH_SUCCESSFUL = typeof POKEMON_API_FETCH_SUCCESSFUL;

export const POKEMON_API_FETCH_FAILED = 'POKEMON_API_FETCH_FAILED';
export type POKEMON_API_FETCH_FAILED = typeof POKEMON_API_FETCH_FAILED;

export const SET_POKEMON_NAMES = 'SET_POKEMON_NAMES';
export type SET_POKEMON_NAMES = typeof SET_POKEMON_NAMES;

export const SET_POKEMON_IMAGES = 'SET_POKEMON_IMAGES';
export type SET_POKEMON_IMAGES = typeof SET_POKEMON_IMAGES;

export const SET_POKEMON_OPTIONS_LIST = 'SET_POKEMON_OPTIONS_LIST';
export type SET_POKEMON_OPTIONS_LIST = typeof SET_POKEMON_OPTIONS_LIST;
