export const SET_POKEMON_NAME = "SET_POKEMON_NAME";
export type SET_POKEMON_NAME = typeof SET_POKEMON_NAME;

export const SET_POKEMON_IMAGE = "SET_POKEMON_IMAGE";
export type SET_POKEMON_IMAGE = typeof SET_POKEMON_IMAGE;

export const FETCH_POKEMON_API = "FETCH_POKEMON_API";
export type FETCH_POKEMON_API = typeof FETCH_POKEMON_API;
